pkg/Makefile, pkg/leo_gateway/Makefile, pkg/leo_gateway/files/leo_gateway.conf, pkg/leo_manager/Makefile, pkg/leo_manager/files/leo_manager.conf.master, pkg/leo_manager/files/leo_manager.conf.slave, pkg/leo_storage/Makefile, pkg/leo_storage/files/leo_storage.conf, rebar.config
SmartOS starting with the 2014Q4 dataset adds package signing this PR adds a generalized makefile (part of fifo_uitls) that contains the logic required to sign packages.
It also updates the config files to the latest state.
It only affects SmartOS builds!
=> Updating the for now SmartOS build process.

git_checkout.sh
`--pull` option allows us to checkout all latest updates from repository easily.
=> Add `--pull` and `--help` option to `git_checkout.sh`

apps/leo_gateway/Makefile, apps/leo_gateway/include/leo_gateway.hrl, apps/leo_gateway/priv/leo_gateway.conf, apps/leo_gateway/priv/leo_gateway.schema, apps/leo_gateway/src/leo_gateway_app.erl, apps/leo_gateway/src/leo_nfs_file_handler.erl, apps/leo_gateway/src/leo_nfs_proto3_server.erl, apps/leo_gateway/src/leo_nfs_state_ets.erl
- https://github.com/leo-project/leofs/issues/327
- https://github.com/leo-project/leofs/issues/598
- https://github.com/leo-project/leofs/issues/599
- https://github.com/leo-project/leofs/issues/611
- https://github.com/leo-project/leofs/issues/613
- https://github.com/leo-project/leofs/issues/614
- https://github.com/leo-project/leofs/issues/627
=> Fixes for 1.3.3

apps/leo_gateway/test/leo_nfs_integration_tests.sh
https://github.com/leo-project/leofs/issues/601
=> leo_gateway: Added Parital Read Write Test for NFS

apps/leo_gateway/src/leo_gateway_http_commons.erl
1. Remove duplicate `leo_gateway_rpc_handler:head`
2. Fix Ranges when Ending Offset is equal to or larger than object size
```
If the last-byte-pos value is
absent, or if the value is greater than or equal to the current
length of the representation data, the byte range is interpreted as
the remainder of the representation (i.e., the server replaces the
value of last-byte-pos with a value that is one less than the current
length of the selected representation).
```
https://tools.ietf.org/html/rfc7233#section-2.1
=> Fix Range Get

apps/leo_gateway/include/leo_gateway.hrl, apps/leo_gateway/src/leo_gateway_s3_api.erl, apps/leo_gateway/test/leo_gateway_web_tests.erl
As the first step, reply the ACL of corresponding Bucket
https://github.com/leo-project/leofs/issues/490
=> gateway: Added Get ACL Support, issue: leofs-project/leofs#490

rel/common/launch.environment, rel/common/launch.sh, rel/leo_gateway/reltool.config, rel/leo_manager/reltool.config, rel/leo_storage/reltool.config
Implementation of https://github.com/leo-project/leofs/issues/638, except for package changes and actual switch to non-privileged user.
=> Deduplication of launch scripts and support for re-defining paths

mv_avs_dir.sh
I've fixed `Restore the simlink of each file` by this commit.
=> leofs: Fix leo-project/leofs/issues/660

apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/src/leo_storage_mq.erl
=> storage: Fix leofs/issues/702 and leofs/issues/704

apps/leo_storage/src/leo_storage_replicator.erl
Add a tag 'leo_storage_replicator' into messages
- Sent from **SubParent** to **Parent**
=> storage: Fixes for #713

apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/src/leo_storage_mq.erl
Fixed https://github.com/leo-project/leofs/issues/702#issuecomment-295563870 by forcing a request from leo_mq to satisfy consistency.N insted of consistency.D.
=> fixes for the delete issue reported on #702

rel/common/launch.sh
This change should be merged at the same time as https://github.com/leo-project/leofs_package/pull/4
Trying to use merged version of leofs_package without this change or merging this change without package script changes will produce broken packages.
Details are in https://github.com/leo-project/leofs/issues/638
=> Run as non-privileged user "leofs" by default

docs/architecture/leo_storage.md
So that information from #708 is not missed
=>  Add a reference to LeoGateway cache settings

apps/leo_gateway/src/leo_gateway_s3_api.erl, apps/leo_gateway/src/leo_nfs_proto3_server.erl, apps/leo_manager/src/leo_manager_sup.erl, apps/leo_storage/priv/leo_storage.conf, docs/admin/system_operations/flow.md
Fixes for
- #556
- #608 
- #609 
- #734 
- #735 
also added the explanation about #556 to the doc.
=> Fixes leo_gateway for 1.3.5

Makefile, bootstrap.sh, mdcr.sh
I'd like to more easily test LeoFS, so I've fixed the files related to LeoFS launch.
=> leofs: To be able to easily build LeoFS for tests by a current user

apps/leo_storage/src/leo_storage_watchdog_sub.erl
Mentioned it in https://github.com/leo-project/leofs/issues/741
=> Fix typo in watchdog logs

apps/leo_gateway/src/leo_gateway_s3_api.erl
In order to comply with the AWS S3 Spec.
=> gateway: fixes for #730

docs/faq/client.md, mkdocs.yml
The preview is here: https://mocchira.github.io/leofs/faq/client/
=> docs: Add the FAQ about LeoFS Clients

apps/leo_gateway/src/leo_gateway_s3_api.erl, apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/src/leo_storage_mq.erl, docs/faq/administration.md
Two fixes there.
- docs: Add the FAQ about timeout during PUT
- Preview can be found here: https://mocchira.github.io/leofs/faq/administration/#what-should-i-do-when-a-timeout-error-happen-during-upload-a-very-large-file
- gateway: Fixes for #770
- storage: Fixes for #769
=> Fixes for 1.3.5

apps/leo_gateway/priv/leo_gateway.conf, apps/leo_manager/priv/leo_manager_0.conf, apps/leo_manager/priv/leo_manager_1.conf, apps/leo_storage/priv/leo_storage.conf, docs/admin/protocols/s3.md, docs/admin/settings/README.md, docs/admin/settings/environment_config.md, docs/admin/settings/leo_storage.md, docs/admin/system_admin/log_management.md, docs/architecture/leo_storage.md, mkdocs.yml, rel/common/launch.sh, rel/leo_gateway/reltool.config, rel/leo_manager/reltool.config, rel/leo_storage/reltool.config, releasenotes/leofs-1.2.md
Implementation of #771. Also fix "Stroage -> Storage" typo around the docs.
=> Support extra config files in addition to main one

docs/installation/cluster.md
You can preview the doc on https://mocchira.github.io/leofs/installation/cluster/#configure-an-endpoint.
Background: 
Recently lots of questions about endpoints have been dropped on community channels so I decided to put some docs that help them understand endpoints.
=> docs: Add the explanation on endpoints

apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/src/leo_manager_console.erl, apps/leo_manager/src/leo_manager_del_bucket_handler.erl, apps/leo_manager/src/leo_manager_mnesia.erl, apps/leo_storage/src/leo_storage_handler_del_directory.erl, apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/src/leo_storage_mq.erl, leofs-adm
Fix all issues described at https://github.com/leo-project/leofs/issues/725#issuecomment-315966669
=> Fixes for delete-bucket related things

apps/leo_manager/src/leo_manager_formatter_text.erl, apps/leo_storage/src/leo_storage_handler_del_directory.erl, docs/admin/system_operations/s3.md
The preview can be seen on https://mocchira.github.io/leofs/admin/system_operations/s3/
=> docs: Add the documents related to delete-bucket-stats

docs/admin/protocols/nfs_v3.md
Preview is here: https://mocchira.github.io/leofs/admin/protocols/nfs_v3/
=> docs: fix the comment on how to mount the bucket via NFS

docs/admin/system_operations/s3.md
Preview: https://mocchira.github.io/leofs/admin/system_operations/s3/#retrieve-a-list-of-the-ongoing-delete-buckets-delete-bucket-stats
=> docs: fix the duration how log the delete-bucket records exist

rel/common/launch.sh
=> Make sure sudo always sets correct $HOME

.gitignore, rel/common/launch.sh, rel/leo_manager/reltool.config, rel/service/90-leofs.preset, rel/service/leofs-epmd.service.pre, rel/service/leofs-epmd.socket, rel/service/leofs-gateway.service, rel/service/leofs-manager-master.service, rel/service/leofs-manager-slave.service, rel/service/leofs-storage.service
=> Foreground launch mode and systemd unit files

rel/common/launch.sh, rel/common/leofs.conf
Part of #791 
Needs to be merged before package changes using this feature
=> Optionally read config from /etc/leofs

docs/admin/settings/environment_config.md, docs/admin/system_admin/migration.md, docs/admin/system_operations/systemd.md, docs/installation/quick.md, mkdocs.yml
Part of #790 
If 1.3.8 will be released, all references in 1.4.0 will have to be changed to 1.3.8 here..
=> Documentation for systemd services and upgrade procedure

docs/faq/administration.md
Preview: https://mocchira.github.io/leofs/faq/administration/#why-doesnt-leofs-adm-respond-to-a-command-like-leofs-adm-status
=> docs: Add the way to handle netcat trouble into FAQ

apps/leo_gateway/priv/leo_gateway.schema
Fix for https://github.com/leo-project/leofs/issues/747#issuecomment-332865761
=> gateway: Disable checking the disk usage with disksup

apps/leo_gateway/include/leo_gateway.hrl, apps/leo_gateway/include/leo_http.hrl, apps/leo_gateway/src/leo_gateway_s3_api.erl
=> gateway: Handle Bucket Already Exists with HTTP 409 Conflict Reply

docs/admin/system_admin/migration.md, docs/admin/system_admin/multiple_nodes.md, docs/admin/system_admin/persistent_configuration.md, mkdocs.yml
Documentation for #791 and #792
=> Documentation for /etc/leofs configs and multiple node instances

apps/leo_gateway/include/leo_http.hrl, apps/leo_gateway/src/leo_gateway_s3_api.erl, apps/leo_manager/src/leo_manager_api.erl
This PR has fixed below issues
- #845 
- #851 
- #858 
each commit corresponds to each fix.
=> Several minor fixes for 1.4

apps/leo_gateway/include/leo_http.hrl, apps/leo_gateway/src/leo_gateway_http_commons.erl, apps/leo_gateway/src/leo_gateway_rest_api.erl, apps/leo_gateway/src/leo_gateway_s3_api.erl, docs/admin/system_admin/health_check.md, mkdocs.yml
based on feedback from @vstax 
- Change the URL to _leofs_adm/ping
- Make the URL available in REST mode
- Add the documentation about Health Check
=> Modify the health check specification

apps/leo_gateway/include/leo_gateway.hrl, apps/leo_gateway/rebar.config, apps/leo_gateway/src/leo_gateway_api.erl, apps/leo_gateway/src/leo_gateway_app.erl, apps/leo_gateway/src/leo_gateway_s3_api.erl, apps/leo_gateway/test/leo_gateway_rpc_handler_tests.erl, apps/leo_gateway/test/leo_gateway_web_tests.erl, apps/leo_gateway/test/leo_nfs_readdir_state_ets_server_tests.erl, apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/rebar.config, apps/leo_manager/src/leo_manager_app.erl, apps/leo_manager/src/leo_manager_sup.erl, apps/leo_storage/include/leo_storage.hrl, apps/leo_storage/rebar.config, apps/leo_storage/src/leo_storage_api.erl, apps/leo_storage/src/leo_storage_app.erl, apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/test/leo_storage_handler_object_tests.erl, apps/leo_storage/test/leo_storage_mq_tests.erl, rel/common/launch.environment, rel/leo_gateway/reltool.config, rel/leo_manager/reltool.config, rel/leo_storage/reltool.config
https://github.com/leo-project/leo_logger/pull/5
https://github.com/leo-project/lager/pull/1
#729
=> leofs: Switch logger to lager backend

apps/leo_storage/src/leo_storage_mq.erl
Part of the fix for https://github.com/leo-project/leofs/issues/880.
=> storage: Fix recover-node to deal with hardware-failures on multiple nodes

docs/faq/limits.md
For #880 
Preview: https://mocchira.github.io/leofs/faq/limits/#features
=> docs: Add the limitation about recover-node

apps/leo_gateway/include/leo_gateway.hrl, apps/leo_gateway/include/leo_http.hrl, apps/leo_gateway/priv/leo_gateway.schema, apps/leo_gateway/src/leo_gateway_app.erl, apps/leo_gateway/src/leo_gateway_s3_api.erl
Temporary solution for #903 until #719 will be fixed.
Note: 
As @vstax suggested on https://github.com/leo-project/leofs/issues/903#issuecomment-340792709,
this parameter should be hidden for safe so it's only available on .schema (no mention on .conf file on purpose).
=> gateway: Fix for #903

apps/leo_gateway/src/leo_gateway_s3_api.erl
https://github.com/leo-project/leofs/issues/490
=> gateway: handle get object ACL when object is cached

apps/leo_gateway/include/leo_http.hrl, apps/leo_gateway/src/leo_gateway_s3_api.erl, docs/admin/protocols/s3.md
=> gateway: handle get bucket location, as us-east-1

apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/src/leo_manager_api.erl
=> manager: convert system conf from old cluster, compatibility check,

apps/leo_manager/src/leo_manager_api.erl
#914 
https://github.com/leo-project/leo_redundant_manager/pull/8
=> manager: fix for leo_project/leofs#914

apps/leo_gateway/src/leo_gateway_s3_api.erl
Before merging this PR, https://github.com/leo-project/leo_commons/pull/10 should be merged.
also I'd like to ask @windkit to benchmark with this PR on RIT cluster for safe as this PR relatively use much CPU time than the previous version.
=> gateway: Fix for #926

docs/admin/system_admin/multiple_nodes.md
As described here: https://github.com/leo-project/leofs/issues/792#issuecomment-343558643
Can be previewed at https://vstax.github.io/leofs/admin/system_admin/multiple_nodes/
=> Documentation fixes for running multiple nodes

.gitignore, Makefile, apps/leo_gateway/rebar.config, apps/leo_gateway/src/leo_gateway_app.erl, apps/leo_manager/rebar.config, apps/leo_manager/src/leo_manager_sup.erl, apps/leo_storage/rebar.config, apps/leo_storage/src/leo_storage_app.erl, make_reltool.sh, rel/leo_gateway/reltool.config.in, rel/leo_manager/reltool.config.in, rel/leo_storage/reltool.config.in, rel/service/leofs-gateway.service, rel/service/leofs-manager-master.service, rel/service/leofs-manager-slave.service, rel/service/leofs-storage.service
Implementation of #840; requires https://github.com/leo-project/leo_commons/pull/11 to be merged first.
=> Optionally build with sd-notify library and send notification to systemd

apps/leo_storage/src/leo_storage_app.erl
Because of the below lines quoted from https://github.com/leo-project/leofs/issues/840#issuecomment-352627443
> Now in case of the start failure due to lack of managers, leo_backend_db in leo_storage failed to produce the state file that includes the number of keys stored in leveldb so leo_backend_db have to iterate the all records on the next startup so this cause startup leo_storage to be slow down. I will send PR later.
This PR will fix the problem by delaying the state file deletion after checking the liveness of managers.
=> storage: Fix leo_storage startup can take much time more than necessary

apps/leo_storage/src/leo_storage_app.erl
Before merging this PR, https://github.com/leo-project/leo_watchdog/pull/9 should be merged to make this change take effect.
=> storage: Fix for #960 and #812

apps/leo_storage/src/leo_storage_handler_object.erl
Call fetch_by_key_in_parallel in case handling delete-bucket
=> storage: Fix for #764

apps/leo_manager/src/leo_manager_console.erl, leofs-adm
This PR should be merged after https://github.com/leo-project/leo_s3_libs/pull/12 get merged and tagged.
=> leofs: Fix #964

docs/admin/settings/leo_gateway.md
Preview is available on https://mocchira.github.io/leofs/admin/settings/leo_gateway/#configurations-which-may-affect-the-cache-behavior
=> docs: Fix #997

docs/admin/settings/leo_storage.md
The preview can be found on https://mocchira.github.io/leofs/admin/settings/leo_storage/#configuration-which-can-affect-load-and-cpu-usage
=> docs: Add a section that Configuration which can affect Load and CPU usage into LeoStorage Settings

apps/leo_gateway/rebar.config, apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/rebar.config, apps/leo_manager/src/leo_manager_api.erl, apps/leo_manager/src/leo_manager_console.erl, apps/leo_storage/rebar.config, apps/leo_storage/src/leo_storage_api.erl, apps/leo_storage/src/leo_storage_mq.erl, docs/admin/system_operations/data.md, leofs-adm
Fix for #983.
This PR should be merged after https://github.com/leo-project/leo_object_storage/pull/26 get merged, bumped and updated each rebar.config according to the latest versions.
The document for recover-disk can be previewed on https://mocchira.github.io/leofs/admin/system_operations/data/
=> leofs: Add recover-disk command for #983

apps/leo_gateway/src/leo_gateway_s3_api.erl
=> gateway: Fix for #1021

apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/priv/leo_manager_0.conf, apps/leo_manager/priv/leo_manager_0.schema, apps/leo_manager/priv/leo_manager_1.conf, apps/leo_manager/priv/leo_manager_1.schema, apps/leo_manager/src/leo_manager_sup.erl
With the default setting, listen address will be bound to the loopback address and also the address can be configurable through console.bind_address for those who want to listen any other.
=> manager: Fix #891

docs/admin/settings/leo_manager.md
=> docs: Add the explanation about console.bind_address

docs/admin/settings/cluster.md, docs/admin/system_operations/data.md
- For scrub, Preview can be found on https://mocchira.github.io/leofs/admin/system_operations/data/#use-cases
- For rebalance with extremely high consistency level, Preview can be found on https://mocchira.github.io/leofs/admin/settings/cluster/#data-availability-of-consistency-level
=> Add the documentations for 1.4.1

apps/leo_gateway/include/leo_http.hrl, apps/leo_gateway/src/leo_gateway_app.erl, apps/leo_gateway/src/leo_gateway_http_commons.erl, apps/leo_gateway/src/leo_gateway_rest_api.erl, docs/admin/system_admin/integration.md, rel/common/launch.sh, rel/common/nodetool
Previews for the doc
- https://mocchira.github.io/leofs/admin/system_admin/integration/#how-to-test-whether-a-conf-file-has-any-errors
- https://mocchira.github.io/leofs/admin/system_admin/integration/#how-to-reload-a-conf-file-on-the-fly
=> Fix issue673/1031 and its documentation

docs/RFCS/data_protection/ssec.md, docs/RFCS/template.md, mkdocs.yml
- [Server Side Object Encryption with Customer-Provided Encryption Keys (SSE-C)](https://yosukehara.github.io/leofs/RFCS/data_protection/ssec/)
- Link: https://github.com/leo-project/leofs/issues/114
=> [doc][rfc] Add a documentation of SSE-C
