leo-project/leofs

pkg/leo_manager/Makefile, pkg/leo_manager/pre_pkg
The makefile submitted did put the leo_manager into /opt/local/loe_manager/leo_manager, this patch corrects this and puts it into the propper place
=> Fixed bug in SmartOS leo_manager makefile 

priv/mon/README.md, priv/mon/leofs-mon, priv/mon/template_12/leofs-gateway.grafana, priv/mon/template_12/leofs-gateway.telegraf, priv/mon/template_12/leofs-manager.grafana, priv/mon/template_12/leofs-manager.telegraf, priv/mon/template_12/leofs-storage.grafana, priv/mon/template_12/leofs-storage.telegraf
Current "leofs-mon" generate a grafana setting file for schema version "**6**", 
but latest grafana's schema version is "**12**", so It does not work.
I added new template to adjust latest grafana(v3.0.4).
And add some option to leofs-mon.
- [-data_source <datasource-name>]: enable to set data_source param
- [-schema12]: With this option, leofs-mon use new template
- [-api]: With this option, leofs-mon generate config file for grafana api.
(http://docs.grafana.org/reference/http_api/)
Ex.) command of make dashboard via api
````
curl http://{GRAFANA_SERVER_IP}:3000/api/dashboards/db \
-H "Authorization: Bearer ${API_KEY}" \
-H "Accept: application/json" \
-H "Content-type: application/json" \
-X POST -d @{****_at_***.grafana}
````
Please check it.
(I didn't change the telegraf side) …
=> adjust for latest grafana version

README.md
```
vagrant@vagrant-ubuntu-trusty-64:/tmp$ tar xzf libatomic_ops-7.2d.tar.gz
vagrant@vagrant-ubuntu-trusty-64:/tmp$ ls -l
total 232
drwxr-xr-x 6 vagrant vagrant   4096 Aug  9  2012 libatomic_ops-7.2
-rw-rw-r-- 1 vagrant vagrant 230358 Jun  9 20:26 libatomic_ops-7.2d.tar.gz
```
=> There's a small bug in installation instruction about libatomic

apps/leo_manager/src/leo_manager_api.erl
Delete a bucket in LeoFS should also remove all the objects in it, but from 1.3.0, those objects are not removed. Creating a bucket with the same name and the file can then be easily accessed. A potential security problem.
https://github.com/leo-project/leofs/issues/583
=> manager: Fix delete_bucket for 1.3.x

apps/leo_storage/include/leo_storage.hrl, apps/leo_storage/priv/leo_storage.conf, apps/leo_storage/priv/leo_storage.schema, apps/leo_storage/src/leo_storage_handler_object.erl
To fix leo-project/leofs/issues/593, I've implemented an access-log control which depends on `log.access_log_level` configuration as below:
* A part of `leo_storage/priv/leo_storage.conf`:
```ini
log.access_log_level = 0
```
=> storage: To restrict outputing access-logs for fixing leo-project/leofs/issues/593

apps/leo_gateway/src/leo_nfs_file_handler.erl
All tests in leo_nfs_integration_tests.sh passed on ubuntu 16.04LTS.
However Since we couldn't reproduce the actual behavior of nfs client filed on #596 ,
Just in case I'd like a user reporting this issue to confirm this works for him/her.
=> gateway: Fix #596

apps/leo_gateway/src/leo_gateway_api.erl, apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/src/leo_manager_console.erl, apps/leo_manager/src/leo_manager_formatter_json.erl, apps/leo_manager/src/leo_manager_formatter_text.erl, apps/leo_storage/src/leo_storage_api.erl, leofs-adm
```bash
$ ./leofs-adm version all
[Version of Node(s)]
-------+--------------------------+----------------------------------+
type  |           node           |             version              |
-------+--------------------------+----------------------------------+
M    | manager_0@127.0.0.1      | 1.3.3                            |
M    | manager_1@127.0.0.1      | 1.3.3                            |
S    | storage_0@127.0.0.1      | 1.3.3                            |
G    | gateway_0@127.0.0.1      | 1.3.3                            |
-------+--------------------------+----------------------------------+
```
```bash
$ ./leofs-adm version all
[Version of Node(s)]
-------+--------------------------+----------------------------------+
type  |           node           |             version …
```
=> all: handle leofs-adm version all for #643

rel/common/launch.sh
I decided not to change the default behavior (not dumping a crash_dump) as it can be harmful to system as a core dump does.
Instead only add a comment about ERL_CRASH_DUMP_SECONDS notifying users when to uncomment those comments.
=> leofs: Add a comment about ERL_CRASH_DUMP_SECONDS for #667

apps/leo_manager/src/leo_manager_formatter_text.erl
=> manager: Fix leo-project/leofs/issues/695

apps/leo_manager/src/leo_manager_formatter_text.erl
I've fixed the output format of get-bucket command for fixing #698 
```bash
$ ./leofs-adm get-bucket 05236
bucket   | permissions      | redundancy method            | created at
---------+------------------+------------------------------+---------------------------
test     | Me(full_control) | copy, {n:1, w:1, r:1, d:1}   | 2017-04-11 10:53:26 +0900
$ ./leofs-adm update-acl test 05236 public-read-write
OK
$ ./leofs-adm get-bucket 05236
bucket   | permissions                            | redundancy method            | created at
---------+----------------------------------------+------------------------------+---------------------------
test     | Me(full_control), Everyone(read,write) | copy, {n:1, w:1, r:1, d:1}   | 2017-04-11 10:53:26 +0900
$ ./leofs-adm get-buckets
cluster id   | …
```
=> manager: Fix leo-project/leofs/issues/698

apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/priv/leo_manager_0.conf, apps/leo_manager/priv/leo_manager_0.schema, apps/leo_manager/src/leo_manager_api.erl, apps/leo_manager/src/leo_manager_console.erl, apps/leo_manager/src/leo_manager_formatter_json.erl, apps/leo_manager/src/leo_manager_formatter_text.erl, apps/leo_manager/src/leo_manager_sup.erl, apps/leo_manager/src/leo_manager_transformer.erl
I've fixed leo_manager's part of leo-project/leofs/issues/645.
- Added MDC replication related configuration items on `leo_manager/priv/leo_manager_0.conf` as well as on the `CLI output (both text and json)`
- Implemented storing a consistency level and MDC-replication related items into leo_manager's database _(mnesia)_
```
$ leofs-adm status
[System Confiuration]
-----------------------------------+----------
Item                              | Value
-----------------------------------+----------
Basic/Consistency level
-----------------------------------+----------
system version | 1.3.3
cluster Id | leofs_1
DC Id | dc_1
Total replicas | 3
number of successes of R | 1
number of successes of W | 2
number of successes of D | 2
number of rack-awareness replicas | 0
ring size | 2^128 …
```
=> manager: Fix leo_manager's part of leo-project/leofs/issues/645

docs/installation/quick.md
"chown" command is not needed (and bad from security perspective, since it allows running code to change its own binaries on disk) for versions >= 1.3.3, it should be removed. Permissions and ownership are managed by package itself.
=> Remove dangerous "chown" instructions

apps/leo_storage/src/leo_storage_mq.erl
=> storage: Handle not_found to remove unnecessary messages of async-deletion

apps/leo_gateway/rel/reltool.config, apps/leo_manager/priv/leo_manager_0.schema, apps/leo_manager/priv/leo_manager_1.schema, apps/leo_manager/rel/reltool.config, apps/leo_storage/include/leo_storage.hrl, apps/leo_storage/priv/leo_storage.conf, apps/leo_storage/priv/leo_storage.conf.test, apps/leo_storage/rel/reltool.config, apps/leo_storage/src/leo_storage_mq.erl, apps/leo_storage/src/leo_storage_read_repairer.erl, apps/leo_storage/src/leo_storage_replicator.erl, apps/leo_storage/src/leo_sync_local_cluster.erl, apps/leo_storage/test/leo_storage_mq_tests.erl, apps/leo_storage/test/leo_storage_read_repairer_tests.erl, apps/leo_storage/test/leo_storage_replicator_tests.erl
I've modified the all component to fix #761. We need to share data migration tool on the new documentation as below:
> We provide the `db-converter tool` - from `bitcask` to `leveldb` which is [leofs_utils/tools/b2l](https://github.com/leo-project/leofs_utils/tree/develop/tools/b2l).
=> Modified for leo-project/leofs#761

apps/leo_storage/src/leo_storage_mq.erl
A part of fix for **Not all objects from the bucket are deleted on storage node in the end (confirmed)** reported on https://github.com/leo-project/leofs/issues/725#issuecomment-320326336
=> Fix deleted objects can be remained in case compare_between_metadatas return the error tuple

apps/leo_storage/src/leo_storage_handler_del_directory.erl
Confirmed on my dev box with the procedure below.
- add-bucket body/bodytest
- put objects into those two
- delete-bucket body
- confirmed
- objects that belong to body got deleted
- objects that belong to bodytest get remained
also passed all integration test suites for delete-bucket.
=> storage: Fix for #803

apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/src/leo_manager_api.erl, apps/leo_manager/src/leo_manager_console.erl
I've confirmed it has been fixed:
```bash
$ leofs-adm join-cluster manager_10@127.0.0.1:13095 manager_11@127.0.0.1:13096
OK
$ leofs-adm cluster-status
cluster id |   dc id    |    status    | # of storages  |          updated at
-----------+------------+--------------+----------------+-----------------------------
leofs_2    | dc_2       | running      |              4 | 2017-09-06 13:57:12 +0900
$ leofs-adm join-cluster manager_10@127.0.0.1:13095 manager_11@127.0.0.1:13096
[ERROR] Over max number of clusters
$ leofs-adm remove-cluster manager_10@127.0.0.1:13095 manager_11@127.0.0.1:13096
OK
$ leofs-adm cluster-status
[ERROR] Could not get cluster info
$ leofs-adm remove-cluster manager_10@127.0.0.1:13095 manager_11@127.0.0.1:13096
[ERROR] Cluster not found
$ leofs-adm join-cluster …
```
=> manager: Fixes the multi datacenter replication feature for leo-project/leofs/issues/816

apps/leo_storage/priv/leo_storage.schema
This is a part of the fix for https://github.com/leo-project/leofs/issues/592. https://github.com/leo-project/leo_object_storage/pull/11 completes the fix with this PR.
In my test env, The disk full almost never happen with this PR except a few extreme cases like
- The size of AVS is very small (several hundreds MB)
- The PUT throughput is massively high for around one minute
We might reconsider the problem to handle the above extreme cases in future.
=> storage: Change the interval checking the disk usage to 1 minute

apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/src/leo_manager_api.erl, apps/leo_manager/src/leo_manager_console.erl
Fix for https://github.com/leo-project/leofs/issues/817.
In addition to **status ${node}** and **version all** reported on the above issue, **update_property**, **join-cluster** and **dump-ring** could hang up so the explicit timeout has been set to rpc:call in those functions.
=> manager: set timeout to prevent leofs-adm from hanging up

apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/test/leo_storage_handler_object_tests.erl
This reverts commit a9ba5a8eea4d16499d457f78909ce3faf6c7d6a4 to fix https://github.com/leo-project/leofs/issues/821.
=> Revert "storage: Pass Max Keys to backend db for prefix_search"

docs/faq/administration.md
Answer to the question on https://groups.google.com/d/msg/leoproject_leofs/OcKOQ0Q4qIc/PxRlM7XtAwAJ
You can preview the doc on https://mocchira.github.io/leofs/faq/administration/#when-will-dns-lookups-for-nodes-in-a-cluster-happen
=> docs: Add the FAQ about when DNS lookups happen in a cluster

rel/common/launch.sh, rel/service/leofs-gateway.service, rel/service/leofs-manager-master.service, rel/service/leofs-manager-slave.service, rel/service/leofs-storage.service
Implementation of #792. Works only when using config from /etc/leofs.
Also increased "max open files" limit (systemd services only) for leo_gateway (for handling multiple connections) and for leo_storage (required when having > ~40 AVS files).
=> Support running multiple instances of the same node

.gitignore
IMO the ```launch.environment```  should be ignored since it changes based on user build env (eg: username given while launching docker)
=> Ignoring a pre-generated file

README.md
To clean up the instructions for developers
1. Use default build option Erlang OTP
2. Download Erlang OTP package instead of building from source
https://github.com/leo-project/leofs/issues/850
=> leofs: Cleaned up instruction to developers

apps/leo_gateway/src/leo_gateway_http_commons.erl
```bash
leofs@cat2neat:leofs.1.3.5$ curl -v -H 'If-Modified-Since: Fri, 06 Oct 2017 07:36:53 GMT' http://localhost:8080/leofs-adm/CHANGELOG.md -o CHANGELOG.md.dl
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /leofs-adm/CHANGELOG.md HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> If-Modified-Since: Fri, 06 Oct 2017 07:36:53 GMT
>
< HTTP/1.1 304 Not Modified
< Connection: keep-alive
< Date: Fri, 06 Oct 2017 07:52:46 GMT
< Content-Length: 0
< Server: LeoFS
<
0 …
```
=> gateway: Handle If-Modified-Since a part of fix for #848

apps/leo_manager/src/leo_manager_console.erl, apps/leo_storage/src/leo_storage_api.erl, apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/src/leo_storage_mq.erl
Note: funcs added for debug/test can be used on remote_console and also will be used at leofs_test2 to increase the test coverage like
- https://github.com/leo-project/leofs/issues/875
=> Fix recover-(file|node) issues and add the funcs for debug/test

rel/common/launch.environment, rel/common/launch.sh, rel/common/leofs-limits.conf
When installed by rpm/deb package (https://github.com/leo-project/leofs_package/pull/10), limits config raises default limit of 1024 open files, which isn't enough when having many AVS files on storage or high load on gateway. It is already raised for systemd services, this is only required when launching directly through script.
Also contains workaround for Ubuntu sudo settings (#883).
=> Increase open files limit

rel/common/launch.environment, rel/common/launch.sh
It can be set in environment file or systemd unit file and script will pick the setting.
=> Make ERL_CRASH_DUMP_SECONDS configurable without changing main script

apps/leo_gateway/src/leo_gateway_http_commons.erl, apps/leo_gateway/src/leo_gateway_s3_api.erl, apps/leo_storage/src/leo_storage_handler_object.erl, apps/leo_storage/src/leo_storage_mq.erl, apps/leo_storage/src/leo_sync_remote_cluster.erl
I've fixed #835 issue, there are root causes at LeoGateway and LeoStorage, then tested its issue as below:
```bash
$ leofs-adm join-cluster manager_10@127.0.0.1:13095 manager_11@127.0.0.1:13096
OK
$ ./leofs-adm -p 10110 update-acl test 05236 public-read
OK
$ ./leofs-adm update-acl test 05236 public-read
OK
```
```bash
$ s3cmd put --add-header=x-amz-meta-testkey:testvalue ./rebar.config s3://test/
./rebar.config -> s3://test/rebar.config  [1 of 1]
1090 of 1090   100% in    0s    54.38 kB/s  done
```
```bash
curl -v http://localhost:8080/test/rebar.config > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* connect …
```
=> Fixed for leo-project/leofs#835

docs/admin/settings/environment_config.md, docs/admin/system_admin/migration.md, docs/admin/system_admin/multiple_nodes.md, docs/admin/system_admin/persistent_configuration.md, docs/admin/system_operations/systemd.md
Can be previewed at https://vstax.github.io/leofs/ but it's really just a 1.4.0 -> 1.3.8 change where relevant
=> Change documentation to prepare for 1.3.8 release

apps/leo_storage/include/leo_storage.hrl, apps/leo_storage/priv/leo_storage.conf, apps/leo_storage/priv/leo_storage.schema, apps/leo_storage/src/leo_storage_app.erl, apps/leo_storage/src/leo_storage_msg_collector.erl, apps/leo_storage/src/leo_storage_watchdog_msgs.erl
Fixed #912 and also fixed existing bugs (stored a slow operation message as a timeout one, raised items were not cleared)
=> storage: Fix for #912

apps/leo_gateway/src/leo_gateway_s3_api.erl
Output the actual reason (not_found or {error, Cause}) rather than invalid_metadata which makes it difficult for sysadmin to analyze log files.
=> gateway: make the error message readable

bootstrap.sh
This PR enables developers to iterate integration tests as quick as possible.
=> leofs: Improve the boot time on bootstrap.sh by using wait_ready instead of sleep 30

apps/leo_gateway/src/leo_large_object_get_handler.erl
TCP Connection get reset immediately with additional error lines like below
```erlang
[E]     gateway_0@127.0.0.1     2017-11-30 13:42:54.829985 +0900        1512016974      null:null       0       gen_server <0.1978.0> terminated with reason: not_found in leo_large_object_get_handler:handle_loop/3 line 271
[E]     gateway_0@127.0.0.1     2017-11-30 13:42:54.830155 +0900        1512016974      null:null       0       CRASH REPORT Process <0.1978.0> with 1 neighbours exited with reason: not_found in leo_large_object_get_handler:handle_loop/3 line 271 in gen_server:terminate/7 line 812
[E]     gateway_0@127.0.0.1     2017-11-30 13:42:54.830338 +0900        1512016974      null:null       0       Ranch listener leo_gateway_s3_api terminated with reason: not_found in …
```
=> gateway: Fix for #894

apps/leo_manager/src/leo_manager_del_bucket_handler.erl, apps/leo_storage/src/leo_storage_handler_del_directory.erl
As expected, the frequency of stop proceeding get decreased (almost never happen in my tests and even if it happened, the error get disappeared immediately).
=> leofs: Fix for #892

Makefile
#953 added a bashism which breaks build on certain systems (e.g. Debian and Ubuntu with "dash" shell).
Alternative solution would be using SHELL=/bin/bash in Makefile but that would bring some change for FreeBSD and Solaris systems, I think it's better to just remove it.
=> Remove bashism from Makefile (fix Debian/Ubuntu/FreeBSD build)

make_reltool.sh
Works correctly on non-Linux systems now (tested on FreeBSD 10 and Solaris 11.3).
=> Make "make_reltool.sh" more portable

apps/leo_storage/rebar.config, apps/leo_storage/src/leo_storage_mq.erl, apps/leo_storage/src/leo_storage_read_repairer.erl, apps/leo_storage/src/leo_sync_local_cluster.erl, apps/leo_storage/test/leo_storage_mq_tests.erl
Should be merged after https://github.com/leo-project/leo_object_storage/pull/20 got merged.
and also just happens to notice now recover-node also doesn't work in case metadata is valid and avs is broken. I will update PR later for that. (leo_sync_local_cluster:store/2 has to deal with the case using leo_object_storage_api:head_with_check_avs)
=> storage: Fix for #543 and #546

bootstrap.sh
This PR makes `bootstrap.sh start` faster by starting leo_storage in parallel.
As a result, Iterating integration tests take less time.
=> leofs: Make bootstrap.sh start faster

apps/leo_storage/src/leo_storage_handler_object.erl
Fixed https://github.com/leo-project/leofs/issues/989.
Confirmed with 
- object_storage.threshold_of_slow_processing = 300
- watchdog.msgs.is_enabled = true
in leo_storage.conf and basho_benched to yield {error, unavailable}.
=> storage: Fix #989

apps/leo_manager/include/leo_manager.hrl, apps/leo_manager/src/leo_manager_api.erl
LeoManager rejects a request of `recover-cluster <CLUSTER_ID>` when not joining a remote cluster as below:
```
$ ./leofs-adm status
[System Confiuration]
-----------------------------------+----------
Item                              | Value
-----------------------------------+----------
Basic/Consistency level
-----------------------------------+----------
system version | 1.4.0
cluster Id | leofs_1
DC Id | dc_1
Total replicas | 1
number of successes of R | 1
number of successes of W | 1
number of successes of D | 1
number of rack-awareness replicas | 0
ring size | 2^128
-----------------------------------+----------
Multi DC replication settings
-----------------------------------+----------
[mdcr] max number of joinable DCs | 2
[mdcr] total replicas per a DC    | 1
[mdcr] number of …
```
=> manager: Resolve leo-project/leofs/issues/1003

leofs-adm
I've found `leofs-adm` commands cannot terminate on Ubuntu-18.04.
=> [leofs] To be able to correctly terminate leofs-adm's commads on Ubuntu-18.04
